### ISSUE TITLE
Selecting layers with same fill not working

### ISSUE THREAD

**Issue by lev-gubin** [wonderbit/sketch-select-similar-layers#19]
File where plugin does not work: [tworectangles.zip](https://github.com/wonderbit/sketch-select-similar-layers/files/1213835/tworectangles.zip)

**Steps for reproduce:**
1. Select layer «1»
2. Ctrl+Alt+1 or select Fill Color in Plugins menu

**Result:** nothing is selected.

Log from Console:
```
TypeError: layer.style is not a function. (In 'layer.style()', 'layer.style' is undefined)
line: 145
sourceURL: /Users/lev/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Select Similar Layers.sketchplugin/Contents/Sketch/script.cocoascript
column: 34
```

**Comment by sdaitzman** [comment]
I am experiencing the same issue on Sketch v46.1

**Comment by thierryc** [comment]
Same issue on Sketch v46.2 
I fix-it in my pull resquest #20

**Comment by thierryc** [comment]
Please add a comment to the pull request (#20) !

**Comment by thierryc** [comment]
You can download my version https://github.com/thierryc/sketch-select-similar-layers

**Comment by gamecubate** [comment]
@thierryc, your fork works. Thanks!

**Comment by thierryc** [comment]
Well! Thank you for the feedback.

**Comment by thierryc** [comment]
@wonderbit this issue is closed.
