### ISSUE TITLE
What is name and class?

### ISSUE THREAD

**Issue by abinashmohanty** [wonderbit/sketch-select-similar-layers#23]
It's an amazing and must have sketch plugins. By the way, could you please explain the major difference in between selecting a **Name** vs **Name and Class** ?

**Comment by wonderbit** [comment]
@abinashmohanty **Name** selects every layer with the same name while **Name and Class** selects layers which have the same name and are of the same class or type (shapes, text, groups, images, etc.). Suppose you have two shape layers (rectangles, ovals, etc.) called "Example", and two text layers called "Example" as well. With the **Name** one, all four would be selected, but with the **Name and Class**, it would select only the text layers or only the shape layers. This works also with layer groups and images.
