### ISSUE TITLE
[Feature request] Select similar option for single artboard

### ISSUE THREAD

**Issue by mheesakkers** [wonderbit/sketch-select-similar-layers#31]
It would be great to have the functionality to select similar layers in one single artboard ;)
Hope you can implement this!

**Comment by wonderbit** [comment]
At the beginning of the plugin file, there's a variable called "selectInAllArtboards", which controls this. When set to true it selects in all the artboards and when set to false it will only select in the current artboard.

Anyway, I decided to change the default value to false. If you download the plugin again it'll select in a single artboard.

**Comment by mheesakkers** [comment]
Ah great, thanks!
