### ISSUE TITLE
Used to select all similar layers in my entire page, now it only selects similar layers within specific artboard

### ISSUE THREAD

**Issue by joelandrewbrown** [wonderbit/sketch-select-similar-layers#34]
I have been using your plugin daily to select all classes (types) that are symbols, so I can bulk detach all symbols in my document before pushing via Craft Sync to Invision (it's a long story).

I used to be able to select all similar class types that are symbols within the entire page I'm on. Now it only selects all within a specific artboard (I have about 50 + artboards, meaning I'd have to "select all by type" 50 times.

Hope this makes sense! I've been loving the plugin. I just updated to version 1.4.1 today, which began this issue for me.

Thanks!

**Comment by joelandrewbrown** [comment]
Also - Sketch 52.6

**Comment by wonderbit** [comment]
Hi @joelandrewbrown,

I just updated the plugin to allow both select in current artboard and select in all the arboards. Please update your plugin to 1.5.

The existing keyboard shortcuts (e.g. ⌃ ⌥ 1) will still select layers in the current artboard though. But you can add the shift key to that (⌃ ⌥ ⇧ 1) and it'll select in all artboards.

Let me know if you encounter any other problems.

**Comment by joelandrewbrown** [comment]
Thank you so much! You truly just saved my day! Thanks for being awesome!
