### ISSUE TITLE
Select by fill color doesn't work (Plugin v1.6) (Sketch 61)

### ISSUE THREAD

**Issue by lfs-designsystem** [wonderbit/sketch-select-similar-layers#36]
Select by fill colour doesn't appear to be working in version 1.6 of the plugin in Sketch 61. I can't be certain as to whether it works in other versions of Sketch at this moment. But other features within the plugin seem to behave fine. Colour seems to be the only one not working. Happy to test further or provide more info if required.

**Comment by alvathoni** [comment]
+1

**Comment by wonderbit** [comment]
It should be fixed now, sorry about that :)

**Comment by alvathoni** [comment]
It worked! Thanks to @wonderbit

**Comment by lfs-designsystem** [comment]
Woo! Yes it works. Thanks heaps @wonderbit!
