### ISSUE TITLE
3.7.1 support?

### ISSUE THREAD

**Issue by username1290** [wonderbit/sketch-select-similar-layers#5]
Hi, does this work for anyone in 3.7.1?

**Comment by wonderbit** [comment]
@sogen Works for me 😊

**Comment by username1290** [comment]
@wonderbit what version of OSX? I'm on Yosemite 10.10.5
I tried reinstalling (downloaded zip file, double clicked it to install) it but still can't get it to work

**Comment by wonderbit** [comment]
@sogen What are you experiencing exactly? Please note that, as of today, the plugin will only select similar objects in the same artboard.

**Comment by username1290** [comment]
It seems like the plugins runs, looks busy for a couple of seconds, 
but after it "finishes" nothing got selected

**Comment by luclemo** [comment]
Same issue as @sogen in 3.8.3
Any updates on this?
